### PR TITLE
Added notification counter badge to app taskbar icon

### PR DESCRIPTION
**Pull request by Novack**
Typical Windows taskbar icon counter badge functionality.
image

### CODE REVIEW

**Review by amilich — COMMENTED** [review]
Looks awesome.

**Review by amilich — COMMENTED** [review]
Looks great. Just tested. Seeing this right now:

image

Is it possible I've messed something up in testing or configuration?

**Review by amilich — APPROVED** [review]
NVM. Looks good.

**Comment by Novack** [comment]
Looks like the standard icon is missing, but the overlay is working...
If you tweaked something in the resources, maybe the skiff logo got removed (see image).
image

Otherwise, maybe the TaskbarItemInfo needs some other parameter on Windows 11 (Im still on Win10, thus I didn't noticed). If this is the case, I'll investigate!

**Comment by Novack** [comment]
> NVM. Looks good.

Ahh cool then, great, thanks :)

**Comment by amilich** [comment]
[Skiff Installer.msi.zip](https://github.com/skiff-org/skiff-windows-app/files/12705539/Skiff.Installer.msi.zip)
New MSI. Let me know if this looks good. Installer should install over existing version.

**Comment by Novack** [comment]
Btw, the unread counter gives false readings as you move through the different folders, but is related to the messages received.
Is there another message for the current folder that I can use to filter out the counter if not Inbox?.

**Comment by amilich** [comment]
Great point. I can make it just send inbox unread count?

**Comment by Novack** [comment]
> Great point. I can make it just send inbox unread count?

That would be ideal I think!

**Comment by amilich** [comment]
> > Great point. I can make it just send inbox unread count?
> 
> That would be ideal I think!

Cool. I'll ticket it. The MSI should still be fine.

**Comment by Novack** [comment]
> [Skiff Installer.msi.zip](https://github.com/skiff-org/skiff-windows-app/files/12705539/Skiff.Installer.msi.zip) New MSI. Let me know if this looks good. Installer should install over existing version.

image
Maybe project version needs increase?

**Comment by amilich** [comment]
Will try that

**Comment by amilich** [comment]
[Skiff Installer.msi.zip](https://github.com/skiff-org/skiff-windows-app/files/12705549/Skiff.Installer.msi.zip)
Should be upgraded to 1.0.8

**Comment by riverar** [comment]
Good start! I think we should consider maybe upgrading this in the future to using the OS provided badging facilities for a more native look/feel. In general, I think we should consider using OS native features over anything homegrown when adding features to this app (i.e. the non-standard notifications should be replaced too).

**Comment by Novack** [comment]
> [Skiff Installer.msi.zip](https://github.com/skiff-org/skiff-windows-app/files/12705549/Skiff.Installer.msi.zip)
> Should be upgraded to 1.0.8

Worked perfectly!

**Comment by Novack** [comment]
> Good start! I think we should consider maybe upgrading this in the future to using the OS provided badging facilities for a more native look/feel. In general, I think we should consider using OS native features over anything homegrown when adding features to this app (i.e. the non-standard notifications should be replaced too).

Hey there. This is using Windows.TaskbarItemInfo.Overlay, is not a custom solution other than rendering the counter on top. Works from Win7 onwards. Do you know of better alternatives?

**Comment by riverar** [comment]
We may want to consider giving the app identity and using WinRT APIs such as the [BadgeUpdateManager](https://learn.microsoft.com/uwp/api/windows.ui.notifications.badgeupdatemanager) 
 and [AppNotificationManager](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.windows.appnotifications.appnotificationmanager?view=windows-app-sdk-1.4). It's more plumbing work to get this all set up though so I'm not suggesting any immediate change here.

**Pull request merged**
