### PR TITLE
Rich notifications

### PR DESCRIPTION
**Pull request by Novack**
Reworked notifications by replacing custom package by native windows notifications. Added rich notifications with custom actions; these actions work on Windows 10 only, so added a simple notification fallback for prior versions.
image

### CODE REVIEW

**Comment by Novack** [comment]
Note that there are currently 5 notification actions available:
- openThread, (will open the window with the selected thread opened)
- markAsRead,
- markAsSpam (currently hidden),
- sendToTrash,
- archive,

All of then send the thread id, using the data model previously discussed. Let me know if any info is needed.

**Comment by amilich** [comment]
This is awesome :)

**Review by amilich — COMMENTED** [review]
how do you listen for these messages from JS?

**Comment by Novack** [comment]
Javascript is not my area, but I understand is something like:
```
window.chrome.webview.addEventListener('message', event => {
    // Handle the message here
    console.log(event.data);
});
```
Then your parse event.data based on the model defined in the classes at the bottom of MessageProcessor class in the desktop app project.

**Comment by amilich** [comment]
> Javascript is not my area, but I understand is something like:
> 
> ```
> window.chrome.webview.addEventListener('message', event => {
>     // Handle the message here
>     console.log(event.data);
> });
> ```
> 
> Then your parse event.data based on the model defined in the classes at the bottom of MessageProcessor class in the desktop app project.

Awesome. Will try it out.

**Comment by Novack** [comment]
Poke me if you need any change or a hand with this one @amilich.

**Comment by amilich** [comment]
> Poke me if you need any change or a hand with this one @amilich.

Will do :)

I need to get the web code side done!

**Comment by amilich** [comment]
What is the JSON structure?

```
            var notificationData = new NotificationActionData()
            {
                Action = action,
                ThreadId = threadId,
            };

            var messageWrapper = new MessageWrapper()
            {
                MsgType = MessageTypes.notificationAction,
                Data = notificationData
            };
```


```
{
 msgType: 'notificationAction'
 data: {
    action: 'archive',
    threadID: string
 }
}
```

**Comment by Novack** [comment]
Yes exactly that (the JsonSerializer uses \\")
`"{
	\"type\":\"notificationAction\",
	\"data\":
			{
				\"Action\":\"markAsRead\",
				\"ThreadId\":\"f395cec4-f040-490a-9465-481be7d62f9b\"
			}
}"`

**Review by amilich — COMMENTED** [review]
draft listener code:
```
  useEffect(() => {
    if (!isWindowsDesktopApp()) {
      return;
    }
    const notificationActionListener = (event: MessageEvent) => {
      // openThread
      // markAsRead
      // markAsSpam
      // sendToTrash
      // archive
      try {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
        const parsedData = JSON.parse(event.data) as { type: string; data: { action: string; threadID: string } };
        if (parsedData.type === 'notificationAction') {
          const { action, threadID } = parsedData.data;
          if (action === 'openThread') {
            setActiveThreadID({ threadID });
          } else if (action === 'markAsRead') {
            void markThreadsAsRead([threadID]);
          } else if (action === 'markAsSpam') {
            void moveThreads([threadID], LABEL_TO_SYSTEM_LABEL[SystemLabels.Spam], [label]);
          } else if (action === 'sendToTrash') {
            void trashThreads([threadID], false);
          } else if (action === 'archive') {
            void archiveThreads([threadID]);
          }
        }
      } catch (err) {
        console.error('Failed to parse data for Windows action', err);
      }
    };
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
    chrome.webview.addEventListener('message', notificationActionListener);
    return () => {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
      chrome.webview.removeEventListener('message', notificationActionListener);
    };
  }, []);
```

**Comment by amilich** [comment]
hopefully will get this out today

**Comment by amilich** [comment]
might need to tweak capitalization

**Comment by Novack** [comment]
> might need to tweak capitalization

Was about to mention that `threadID` and `threadId` need consolidation :)
Also the fields name PascalCasing vs camelCasing.

**Comment by amilich** [comment]
> Action

code is ready - confirming:

```
const parsedData = JSON.parse(event.data) as { type: string; data: { Action: string; threadId: string } };
```
capitalization correct?

**Comment by Novack** [comment]
> capitalization correct?

Both `Action` and `ThreadId` are PascalCase in C# side (because I used the default C# field names as json output), but I missed that the json is actually camelCased in all cases, so let me fix that for consistency.

End result will be `action` and `threadId`.
So in your example, only "Action" needs to be changed to "action".

**Comment by amilich** [comment]
> > capitalization correct?
> 
> Both `Action` and `ThreadId` are PascalCase in C# side (because I used the default C# field names as json output), but I missed that the json is actually camelCased in all cases, so let me fix that for consistency.
> 
> End result will be `action` and `threadId`. So in your example, only "Action" needs to be changed to "action".

Making this change. Will be released to production in ~2 hours.

`action` and `threadId`

**Comment by amilich** [comment]
@Novack released in production!

**Comment by Novack** [comment]
> @Novack released in production!

None of the actions seem to be working, I'll review it later tonight.

**Comment by amilich** [comment]
> > @Novack released in production!
> 
> None of the actions seem to be working, I'll review it later tonight.

oh no :( 

here's the code:

```
 useEffect(() => {
    if (!isWindowsDesktopApp()) {
      return;
    }
    const notificationActionListener = (event: MessageEvent) => {
      // actions available are `openThread`, `markAsRead`, `markAsSpam`, `sendToTrash`, `archive`
      try {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
        const parsedData = JSON.parse(event.data) as { type: string; data: { Action: string; threadId: string } };
        if (parsedData.type === 'notificationAction') {
          const { Action: action, threadId: threadID } = parsedData.data;
          if (action === 'openThread') {
            setActiveThreadID({ threadID });
          } else if (action === 'markAsRead') {
            void markThreadsAsRead([threadID]);
          } else if (action === 'markAsSpam') {
            void moveThreads([threadID], LABEL_TO_SYSTEM_LABEL[SystemLabels.Spam], [label]);
          } else if (action === 'sendToTrash') {
            void trashThreads([threadID], false);
          } else if (action === 'archive') {
            void archiveThreads([threadID]);
          }
        }
      } catch (err) {
        console.error('Failed to parse data for Windows action', err);
      }
    };
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
    chrome.webview.addEventListener('message', notificationActionListener);
    return () => {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
      chrome.webview.removeEventListener('message', notificationActionListener);
    };
  }, []);
```

**Comment by amilich** [comment]
actually maybe action is misspelled here. I might have missed the last push.

**Comment by Novack** [comment]
Yep, seems like Action should be action, and in some places you're using threadID instead of threadId, though not sure if you're referencing ther local value! Will have a detained look in a few minutes.

**Comment by amilich** [comment]
> const { Action: action, threadId: threadID } = parsedData.data;

I just renamed `theadId` to be `threadID` here! That should be fine.

**Comment by Novack** [comment]
Ok just confirmed that if I rename from "action" to "Action" in the desktop project, all actions work.
But for consistency would be better to change that on javascript, what do you think?

Also noted that if you're minimized, but in other folder than Inbox, newMessageNotifications message never arrives. On the other side (as we know already) unreadMailCount changes from folder to folder. So we need the opposite:
- newMessageNotifications to work regardless of what folder the user is at.
- unreadMailCount to only work for inbox.

**Comment by amilich** [comment]
Should be fixed in JS as of ~2 minutes ago

**Comment by amilich** [comment]
I see

**Review by amilich — APPROVED** [review]
approving to get a draft release out today

**Comment by amilich** [comment]
feel free to merge!

**Comment by Novack** [comment]
> feel free to merge!

Thank you! I dont think I have write permissions, lol 
You need to merge :)

**Review by amilich — COMMENTED** [review]
Working on build now, and not seeing the actions. Anything I'm doing wrong?
image

**Comment by amilich** [comment]
also they seem default inside the notifications center, not banner

**Comment by Novack** [comment]
@amilich this may be related to some setting in Windows perhaps? I am on Windows 10, and the notifications look as I have shown on the op. I'll google a bit to see if I am missing some detail on the API.

**Comment by Novack** [comment]
I think something in your build or session failed, even in the notification center, I can see the new rich notifications (1), **but** not for those received by the latest public release which does not include rich notifications (2).
image

**Comment by amilich** [comment]
> I think something in your build or session failed, even in the notification center, I can see the new rich notifications (1), **but** not for those received by the latest public release which does not include rich notifications (2). image

I agree, I will test tonight more.

**Comment by amilich** [comment]
@Novack IT WORKED! Just rebuilt. Sorry for the delay. Building production shortly.

Was doing some work on Quick Aliases until Monday.

**Comment by Novack** [comment]
Awesome news! Thanks for looking into it. Great work on the Quick Aliases!! 👏👏👏

**Comment by amilich** [comment]
Thank you!

Build is here
[Skiff Installer.msi.zip](https://github.com/skiff-org/skiff-windows-app/files/13232549/Skiff.Installer.msi.zip)

**Comment by amilich** [comment]
My installation looks good! Going to make a release now.

**Pull request merged**
